#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RescueMe.Droid.Resource", IsApplication=true)]

namespace RescueMe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int fontPath = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int bar_color = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int bg_bage = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int bg_color = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int btn_color = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int my_blue = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int my_gray = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int my_green = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int my_purple = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int title_color = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowLeft = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowright = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int line = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int profile = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040025
			public const int arrowRight = 2130968613;
			
			// aapt resource value: 0x7f04000a
			public const int back = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int btnAdd = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int btnLogin = 2130968580;
			
			// aapt resource value: 0x7f040026
			public const int btnRegister = 2130968614;
			
			// aapt resource value: 0x7f040000
			public const int calligraphy_tag_id = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int checkbox = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int editText2 = 2130968578;
			
			// aapt resource value: 0x7f040027
			public const int emailRegister = 2130968615;
			
			// aapt resource value: 0x7f04001b
			public const int imageView1 = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int imageView2 = 2130968604;
			
			// aapt resource value: 0x7f04001f
			public const int lblCedula = 2130968607;
			
			// aapt resource value: 0x7f04001d
			public const int lblName = 2130968605;
			
			// aapt resource value: 0x7f040023
			public const int lblPassword = 2130968611;
			
			// aapt resource value: 0x7f040021
			public const int lblTelefono = 2130968609;
			
			// aapt resource value: 0x7f040010
			public const int lblcars = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int line2 = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int linearLayout1 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int linearLayout2 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int linearLayout3 = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int linearLayout4 = 2130968600;
			
			// aapt resource value: 0x7f04000d
			public const int marque = 2130968589;
			
			// aapt resource value: 0x7f040008
			public const int myButton = 2130968584;
			
			// aapt resource value: 0x7f040028
			public const int nameRegister = 2130968616;
			
			// aapt resource value: 0x7f04002a
			public const int passwordConfirmRegister = 2130968618;
			
			// aapt resource value: 0x7f040029
			public const int passwordRegister = 2130968617;
			
			// aapt resource value: 0x7f040019
			public const int scrollView1 = 2130968601;
			
			// aapt resource value: 0x7f040014
			public const int tabHost1 = 2130968596;
			
			// aapt resource value: 0x7f040011
			public const int tableLayout1 = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int tableRow1 = 2130968594;
			
			// aapt resource value: 0x7f040005
			public const int textView1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int textView2 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int textView3 = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int toolbar = 2130968585;
			
			// aapt resource value: 0x7f04001a
			public const int toolbar1 = 2130968602;
			
			// aapt resource value: 0x7f040020
			public const int txtCedula = 2130968608;
			
			// aapt resource value: 0x7f040001
			public const int txtEmail = 2130968577;
			
			// aapt resource value: 0x7f04001e
			public const int txtName = 2130968606;
			
			// aapt resource value: 0x7f040024
			public const int txtPassword = 2130968612;
			
			// aapt resource value: 0x7f040013
			public const int txtRescues = 2130968595;
			
			// aapt resource value: 0x7f040022
			public const int txtTelefono = 2130968610;
			
			// aapt resource value: 0x7f04000b
			public const int txtcars = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int type = 2130968588;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MyCars = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MyRescues = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Profile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int MyCustomTheme = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int button_primary = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
