#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RescueMe.Droid.Resource", IsApplication=true)]

namespace RescueMe.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public const int bar_color = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int my_blue = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int my_gray = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int my_green = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int my_purple = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int title_color = 2131034116;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrowLeft = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrowLeft1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int back = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int btnRegister = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int button1 = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int checkbox = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int editText1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int editText2 = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int emailRegister = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int myButton = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int nameRegister = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int passwordConfirmRegister = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int passwordRegister = 2131165196;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int textView2 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int textView3 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int toolbar1 = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Register = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyCustomTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
